version: 0.0
os: linux
files:
  - source: /app/
    destination: /home/app/HelloWorld
    overwrite: true
  permissions:
  - object: /home/app/HelloWorld
    pattern: "**"
    owner: app
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: app
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: app