version: 0.0
os: linux
files:
  - source: /
    destination: /home/app/serverExpress
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
hooks:
  ApplicationStop:
    - location: deploy/ApplicationStop.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: deploy/BeforeInstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy/AfterInstall.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy/ApplicationStart.sh
      timeout: 60
      runas: ec2-user
